<?php
/**
 * Header Settings
 *
 * @package Maharatri
 */
return array(
	'title'  => esc_html__( 'Header Settings', 'maharatri' ),
	'id'     => 'header_settings',
	'icon'   => 'el el-credit-card',
	'fields' => array(
		array(
			'id'       => 'header-layout',
			'type'     => 'select',
			'title'    => esc_html__( 'Select Header Layout', 'maharatri' ),
			'subtitle' => esc_html__( 'Please select the header style to display.', 'maharatri' ),
			'options'  => array(
				'layout-1' => esc_html__( 'Header Layout 1', 'maharatri' ),
				'layout-2' => esc_html__( 'Header Layout 2', 'maharatri' ),
				'layout-3' => esc_html__( 'Header Layout 3', 'maharatri' ),
				'layout-4' => esc_html__( 'Header Layout 4', 'maharatri' ),
				'layout-5' => esc_html__( 'Header Layout 5', 'maharatri' ),
				'layout-6' => esc_html__( 'Header Layout 6', 'maharatri' ),
			),
			'default'  => 'layout-5',
		),
		array(
			'id'       => 'display_cta',
			'type'     => 'switch',
			'title'    => esc_html__( 'Display Call to Action Button', 'maharatri' ),
			'subtitle' => esc_html__( 'Please choose if you want to display the call to action button in header.', 'maharatri' ),
			'default'  => false,
			'required' => array('header-layout',  '=', array('layout-3', 'layout-4')),
		),
		array(
			'id'       => 'header_cta_title',
			'type'     => 'text',
			'title'    => esc_html__( 'Call to Action Button Title', 'maharatri' ),
			'subtitle' => esc_html__( 'Enter Call to Action title.', 'maharatri' ),
			'required' => array('display_cta',  '=', 'true'),
		),
		array(
			'id'       => 'header_cta_link',
			'type'     => 'text',
			'title'    => esc_html__( 'Call to Action Button link', 'maharatri' ),
			'subtitle' => esc_html__( 'Enter Call to Actionton link.', 'maharatri' ),
			'required' => array('display_cta',  '=', 'true'),
		),
		array(
			'id'       => 'display_info_cta',
			'type'     => 'switch',
			'title'    => esc_html__( 'Display Call to action Info ', 'maharatri' ),
			'subtitle' => esc_html__( 'Please choose if you want to display the call to action info in header.', 'maharatri' ),
			'default'  => false,
			'required' => array('header-layout',  '=', 'layout-5'),
		),
		array(
			'id'       => 'header_cta_info_title',
			'type'     => 'text',
			'title'    => esc_html__( 'Call to Action Info Title', 'maharatri' ),
			'subtitle' => esc_html__( 'Enter Call to Action title.', 'maharatri' ),
			'required' => array('display_info_cta',  '=', 'true'),
		),
		array(
			'id'       => 'header_cta_info_subtitle',
			'type'     => 'text',
			'title'    => esc_html__( 'Call to Action Info Subtitle', 'maharatri' ),
			'subtitle' => esc_html__( 'Enter Call to Action subtitle.', 'maharatri' ),
			'required' => array('display_info_cta',  '=', 'true'),
		),
		array(
			'id'       => 'header_cta_info_icon_class',
			'type'     => 'text',
			'title'    => esc_html__( 'Call to Action Info icon class', 'maharatri' ),
			'subtitle' => esc_html__( 'Enter Call to Action icon class.', 'maharatri' ),
			'required' => array('display_info_cta',  '=', 'true'),
		),
		array(
			'id'       => 'header_cta_info_link',
			'type'     => 'text',
			'title'    => esc_html__( 'Call to Action link', 'maharatri' ),
			'subtitle' => esc_html__( 'Enter Call to Actionton link.', 'maharatri' ),
			'required' => array('display_info_cta',  '=', 'true'),
		),
		array(
			'id'       => 'header-scheme',
			'type'     => 'select',
			'title'    => esc_html__( 'Select Header Color scheme', 'maharatri' ),
			'subtitle' => esc_html__( 'Please select the header color scheme', 'maharatri' ),
			'options'  => array(
				'header-scheme-dark' => esc_html__( 'Dark Scheme', 'maharatri' ),
				'header-scheme-light' => esc_html__( 'Light Scheme', 'maharatri' ),
			),
			'default'  => 'header-scheme-light',
		),
		array(
			'id'       => 'header-position',
			'type'     => 'select',
			'title'    => esc_html__( 'Select Header Position', 'maharatri' ),
			'subtitle' => esc_html__( 'Please select the header position', 'maharatri' ),
			'options'  => array(
				'header-absolute' => esc_html__( 'Absolute', 'maharatri' ),
				'header-relative' => esc_html__( 'Relative', 'maharatri' ),
			),
			'default'  => 'header-relative',
		),
		array(
			'id'       => 'adjust-custom-header-width',
			'type'     => 'switch',
			'title'    => esc_html__( 'Set Custom Header Width', 'maharatri' ),
			'default'  => 0,
			'subtitle' => esc_html__( 'Enable to set custom header width.', 'maharatri' ),
		),
		 array(
      'id' => 'header_content_size_custom',
      'type' => 'slider',
      'title' => esc_html__('Header Custom Content Size', 'maharatri'),
      'subtitle' => esc_html__('Select your desired Header content size', 'maharatri'),
      'min' => 720,
      'step' => 1,
      'max' => 1900,
      'resolution' => 1,
			'display_value' => 'text',
			'required' => array('adjust-custom-header-width',  '=', '1'),
	  ),
		array(
			'id'       => 'sticky-header-enable',
			'type'     => 'switch',
			'title'    => esc_html__( 'Enable sticky header', 'maharatri' ),
			'default'  => false,
			'subtitle' => esc_html__( 'Enable sticky header', 'maharatri' ),
		),
		array(
			'id'       => 'header-sticky-scheme',
			'type'     => 'select',
			'title'    => esc_html__( 'Select Sticky Header Color scheme', 'maharatri' ),
			'subtitle' => esc_html__( 'Please select the sticky header color scheme', 'maharatri' ),
			'options'  => array(
				'header-scheme-dark' => esc_html__( 'Dark Scheme', 'maharatri' ),
				'header-scheme-light' => esc_html__( 'Light Scheme', 'maharatri' ),
			),
			'default'  => 'header-scheme-light',
			'required' => array('sticky-header-enable',  '=', 'true'),
		),
		array(
			'id'          => 'header_sticky_bg',
			'type'        => 'color',
			'title'       => esc_html__( 'Header sticky background color', 'maharatri' ),
			'subtitle'    => esc_html__( 'Set background color for the sticky header.', 'maharatri' ),
			'required' => array('sticky-header-enable',  '=', 'true'),
		),
		array(
			'id'          => 'header_sticky_color',
			'type'        => 'color',
			'title'       => esc_html__( 'Header sticky color', 'maharatri' ),
			'subtitle'    => esc_html__( 'Set color for the sticky header.', 'maharatri' ),
			'required' 		=> array('sticky-header-enable',  '=', 'true'),
			'output'			=> array('.site-header.sticky .site-header-bottom .site-header-bottom-inner > ul > li > a')
		),
		array(
			'id'          => 'header_sticky_color_hover',
			'type'        => 'color',
			'title'       => esc_html__( 'Header sticky color on hover', 'maharatri' ),
			'subtitle'    => esc_html__( 'Set color on hover for the sticky header.', 'maharatri' ),
			'required'		=> array('sticky-header-enable',  '=', 'true'),
			'output'			=> array('.site-header.sticky .site-header-bottom .site-header-bottom-inner > ul > li > a:hover', '.site-header.sticky .site-header-bottom-inner > ul > li.current_page_item > a', '.site-header.sticky .site-header-bottom-inner > ul > li.current-menu-item > a')
		),
		array(
			'id'       => 'display-search-icon',
			'type'     => 'switch',
			'title'    => esc_html__( 'Display Search', 'maharatri' ),
			'default'  => true,
			'subtitle' => esc_html__( 'Enable to display the search in header.', 'maharatri' ),
			'required' => array('header-layout',  '=', array('layout-3'),),
		),
		array(
			'id'       => 'display-user-icon',
			'type'     => 'switch',
			'title'    => esc_html__( 'Display User Icon', 'maharatri' ),
			'default'  => true,
			'subtitle' => esc_html__( 'Enable to display the user icon in header. (WooCommerce Profile)', 'maharatri' ),
			'required' => array('header-layout',  '=', array('layout-3', 'layout-4', 'layout-5'),),
		),
		array(
			'id'       => 'display-collapse-sidebar-icon',
			'type'     => 'switch',
			'title'    => esc_html__( 'Display collapse sidebar', 'maharatri' ),
			'default'  => true,
			'subtitle' => esc_html__( 'Enable to display the collapse sidebar icon in header.', 'maharatri' ),
			'description' => esc_html__( 'Add content in header collapse sidebar using widgets', 'maharatri' ),
			'required' => array('header-layout',  '=', array('layout-1', 'layout-2', 'layout-3')),
		),
		array(
			'id'       => 'display-header-top-menu',
			'type'     => 'switch',
			'title'    => esc_html__( 'Display Top Menu', 'maharatri' ),
			'default'  => true,
			'required' => array('header-layout',  '=', array('layout-4', 'layout-5')),
		),
		array(
			'id'       => 'display-livestream-status',
			'type'     => 'switch',
			'title'    => esc_html__( 'Display Livestream Status', 'maharatri' ),
			'default'  => true,
			'required' => array('header-layout',  '=', array('layout-4', 'layout-5')),
		),
		array(
			'id'       => 'livestream_link',
			'type'     => 'text',
			'title'    => esc_html__( 'Livestream Link', 'maharatri' ),
			'subtitle' => esc_html__( 'Enter livestream video link.', 'maharatri' ),
			'required' => array('display-livestream-status',  '=', 'true'),
		),
		array(
			'id'       => 'livestream_title',
			'type'     => 'text',
			'title'    => esc_html__( 'Livestream Title', 'maharatri' ),
			'subtitle' => esc_html__( 'Enter livestream video title.', 'maharatri' ),
			'required' => array('display-livestream-status',  '=', 'true'),
		),
		array(
			'id'       => 'livestream-header-link-type',
			'type'     => 'select',
			'title'    => esc_html__( 'Livestream Link Type', 'maharatri' ),
			'subtitle' => esc_html__( 'Please select the type for livestream link in header.', 'maharatri' ),
			'options'  => array(
				'popup' => esc_html__( 'Popup (Only for video link)', 'maharatri' ),
				'custom-link' => esc_html__( 'Custom Link (For page)', 'maharatri' ),
			),
			'default'  => 'popup',
			'required' => array('display-livestream-status',  '=', 'true'),
		),
		array(
			'id'       => 'display-header-cart',
			'type'     => 'switch',
			'title'    => esc_html__( 'Display Cart Icon', 'maharatri' ),
			'default'  => true,
		),
		array(
			'id'       => 'display-header-wishlist',
			'type'     => 'switch',
			'title'    => esc_html__( 'Display Wishlist Icon', 'maharatri' ),
			'default'  => true,
			'required' => array('header-layout',  '=', array('layout-4', 'layout-5')),
		),
		array(
			'id'       => 'display-header-prayer-icon',
			'type'     => 'switch',
			'title'    => esc_html__( 'Display Prayer Icon', 'maharatri' ),
			'default'  => false,
			'required' => array('header-layout',  '=', array('layout-4', 'layout-5')),
		),
		array(
			'id'       => 'header_contact_info_phone',
			'type'     => 'switch',
			'default'  => true,
			'title'    => esc_html__( 'Show Phone Contact Info', 'maharatri' ),
			'required' => array('header-layout',  '=', 'layout-3'),
		),
		array(
			'id'       => 'header_contact_info_email',
			'type'     => 'switch',
			'default'  => false,
			'title'    => esc_html__( 'Show Email Contact Info', 'maharatri' ),
			'required' => array('header-layout',  '=', 'layout-3'),
		),
		array(
			'id'       => 'header_contact_info_address',
			'type'     => 'switch',
			'default'  => false,
			'title'    => esc_html__( 'Show Address Contact Info', 'maharatri' ),
			'required' => array('header-layout',  '=', 'layout-3'),
		),
		array(
			'id'          => 'header_bottom_bg',
			'type'        => 'color',
			'title'       => esc_html__( 'Header bottom background color', 'maharatri' ),
			'subtitle'    => esc_html__( 'Set background color for the bottom header.', 'maharatri' ),
		),
		array(
			'id'          => 'header_bottom_color',
			'type'        => 'color',
			'title'       => esc_html__( 'Header bottom color', 'maharatri' ),
			'subtitle'    => esc_html__( 'Set color for the bottom header.', 'maharatri' ),
			'output'			=> array('.site-header .site-header-bottom-inner > ul > li > a', '.header-controls > div > a')
		),
		array(
			'id'          => 'header_bottom_color_hover',
			'type'        => 'color',
			'title'       => esc_html__( 'Header bottom color on hover', 'maharatri' ),
			'subtitle'    => esc_html__( 'Set color on hover for the bottom header.', 'maharatri' ),
			'output'			=> array('.site-header .site-header-bottom-inner > ul > li > a:hover', '.site-header .site-header-bottom-inner > ul > li.current_page_item > a', '.site-header .site-header-bottom-inner > ul > li.current-menu-item > a')
		),
		array(
			'id'          => 'header_submenu_bg',
			'type'        => 'color',
			'title'       => esc_html__( 'Header Submenu background color', 'maharatri' ),
			'subtitle'    => esc_html__( 'Set background color for the submenus.', 'maharatri' ),
		),
		array(
			'id'          => 'header_submenu_color',
			'type'        => 'color',
			'title'       => esc_html__( 'Header Submenu color', 'maharatri' ),
			'subtitle'    => esc_html__( 'Set color for the Submenu.', 'maharatri' ),
			'output'			=> array('.site-header .sigma_mega-menu-item ul.menu li a', '.site-header .site-header-bottom-inner > ul ul.sub-menu li a')
		),
		array(
			'id'          => 'header_submenu_color_hover',
			'type'        => 'color',
			'title'       => esc_html__( 'Header Submenu color on hover', 'maharatri' ),
			'subtitle'    => esc_html__( 'Set color on hover for the Submenu.', 'maharatri' ),
			'output'			=> array('.site-header .sigma_mega-menu-item ul.menu li a:hover', '.site-header .site-header-bottom-inner > ul ul.sub-menu li a:hover')
		),
		array(
			'id'          => 'header_contact_bg',
			'type'        => 'color',
			'title'       => esc_html__( 'Header Contact info background color', 'maharatri' ),
			'subtitle'    => esc_html__( 'Set background color for the contact info.', 'maharatri' ),
			'required' 		=> array('header-layout',  '=', 'layout-1'),
		),
		array(
			'id'          => 'header_contact_bg_color',
			'type'        => 'color',
			'title'       => esc_html__( 'Header Contact info color', 'maharatri' ),
			'subtitle'    => esc_html__( 'Set color for the contact info.', 'maharatri' ),
			'required' 		=> array('header-layout',  '=', 'layout-1'),
			'output'			=> array( '.site-header .contact-info .contact-list span', '.site-header .contact-info .contact-item .contact-list span:last-child', '.site-header .contact-info .contact-item .contact-list span:last-child a' )
		),
	),
);
