<?php
/**
 * Typography settings
 *
 * @package Maharatri
 */
return array(
	'title'            => esc_html__( 'Typography', 'maharatri' ),
	'id'               => 'typography_settings',
	'customizer_width' => '400px',
	'icon'             => 'el el-fontsize',
	'fields'           => array(
		array(
			'id'          => 'body_color',
			'type'        => 'color',
			'title'       => esc_html__( 'Body and Small Text Color', 'maharatri' ),
			'subtitle'    => esc_html__( 'Set color for body and small text', 'maharatri' ),
		),
		array(
			'id'          => 'headings_color',
			'type'        => 'color',
			'title'       => esc_html__( 'Headings Text Color', 'maharatri' ),
			'subtitle'    => esc_html__( 'Set color for the headings', 'maharatri' ),
		),
		array(
			'id'             => 'custom_heading_title_typography',
			'type'           => 'typography',
			'title'          => esc_html__( 'Custom Heading Title Font', 'maharatri' ),
			'subtitle'       => esc_html__( 'Specify typography for heading title.', 'maharatri' ),
			'google'         => true,
			'font-backup'    => true,
			'all_styles'     => false,
			'letter-spacing' => true,
			'text-align'     => false,
			'units'          => 'px',
			'color'          => false,
		),
		array(
			'id'             => 'custom_heading_subtitle_typography',
			'type'           => 'typography',
			'title'          => esc_html__( 'Custom Heading Subtitle Font', 'maharatri' ),
			'subtitle'       => esc_html__( 'Specify typography for heading subtitle.', 'maharatri' ),
			'google'         => true,
			'font-backup'    => true,
			'all_styles'     => false,
			'letter-spacing' => true,
			'text-align'     => false,
			'units'          => 'px',
			'color'          => false,
		),
		array(
			'id'             => 'body_typography',
			'type'           => 'typography',
			'title'          => esc_html__( 'Body Font', 'maharatri' ),
			'subtitle'       => esc_html__( 'Specify typography for body tag.', 'maharatri' ),
			'google'         => true,
			'font-backup'    => true,
			'all_styles'     => false,
			'letter-spacing' => true,
			'text-align'     => false,
			'units'          => 'px',
			'color'          => false,
		),
		array(
			'id'             => 'h1_typography',
			'type'           => 'typography',
			'title'          => esc_html__( 'H1 Headers Typography', 'maharatri' ),
			'subtitle'       => esc_html__( 'Specify typography for h1 tag.', 'maharatri' ),
			'google'         => true,
			'font-backup'    => true,
			'all_styles'     => false,
			'letter-spacing' => true,
			'text-align'     => false,
			'units'          => 'px',
			'color'          => false,
		),
		array(
			'id'             => 'h2_typography',
			'type'           => 'typography',
			'title'          => esc_html__( 'H2 Headers Typography', 'maharatri' ),
			'subtitle'       => esc_html__( 'Specify typography for h2 tag.', 'maharatri' ),
			'google'         => true,
			'font-backup'    => true,
			'all_styles'     => false,
			'letter-spacing' => true,
			'text-align'     => false,
			'units'          => 'px',
			'color'          => false,
		),
		array(
			'id'             => 'h3_typography',
			'type'           => 'typography',
			'title'          => esc_html__( 'H3 Headers Typography', 'maharatri' ),
			'subtitle'       => esc_html__( 'Specify typography for h3 tag.', 'maharatri' ),
			'google'         => true,
			'font-backup'    => true,
			'all_styles'     => false,
			'letter-spacing' => true,
			'text-align'     => false,
			'units'          => 'px',
			'color'          => false,
		),
		array(
			'id'             => 'h4_typography',
			'type'           => 'typography',
			'title'          => esc_html__( 'H4 Headers Typography', 'maharatri' ),
			'subtitle'       => esc_html__( 'Specify typography for h4 tag..', 'maharatri' ),
			'google'         => true,
			'font-backup'    => true,
			'all_styles'     => false,
			'letter-spacing' => true,
			'text-align'     => false,
			'units'          => 'px',
			'color'          => false,
		),
		array(
			'id'             => 'h5_typography',
			'type'           => 'typography',
			'title'          => esc_html__( 'H5 Headers Typography', 'maharatri' ),
			'subtitle'       => esc_html__( 'Specify typography for h5 tag.', 'maharatri' ),
			'google'         => true,
			'font-backup'    => true,
			'all_styles'     => false,
			'letter-spacing' => true,
			'text-align'     => false,
			'units'          => 'px',
			'color'          => false,
		),
		array(
			'id'             => 'h6_typography',
			'type'           => 'typography',
			'title'          => esc_html__( 'H6 Headers Typography', 'maharatri' ),
			'subtitle'       => esc_html__( 'Specify typography for h6 tag.', 'maharatri' ),
			'google'         => true,
			'font-backup'    => true,
			'all_styles'     => false,
			'letter-spacing' => true,
			'text-align'     => false,
			'units'          => 'px',
			'color'          => false,
		),
	),
);
